dataset:
  train:
    type: train
    batch_size: 5
    drop_last: false
    shuffle: true
  valid:
    type: val
    batch_size: 1
    drop_last: false
    shuffle: false
    pixel_per_batch: 512
  test:
    type: test
    batch_size: 1
    drop_last: false
    shuffle: false
    pixel_per_batch: 512